// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs-z7FSBZbIePCAR9ksfTEvq8URHt04ss',
    appId: '1:138121353976:web:71fbe6949f5f96558f790d',
    messagingSenderId: '138121353976',
    projectId: 'turassist-6fdc8',
    authDomain: 'turassist-6fdc8.firebaseapp.com',
    storageBucket: 'turassist-6fdc8.firebasestorage.app',
    measurementId: 'G-8H3205PE1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE9TEDgudXAWBnrNR_c3lrZdnNRrRZpRA',
    appId: '1:138121353976:android:f633c63a1143590f8f790d',
    messagingSenderId: '138121353976',
    projectId: 'turassist-6fdc8',
    storageBucket: 'turassist-6fdc8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQi45pOdLuVx7doWBGAf2LNTTk5jWnaWg',
    appId: '1:138121353976:ios:2070d94401d0dd328f790d',
    messagingSenderId: '138121353976',
    projectId: 'turassist-6fdc8',
    storageBucket: 'turassist-6fdc8.firebasestorage.app',
    iosBundleId: 'com.natanzdev.turassist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQi45pOdLuVx7doWBGAf2LNTTk5jWnaWg',
    appId: '1:138121353976:ios:2070d94401d0dd328f790d',
    messagingSenderId: '138121353976',
    projectId: 'turassist-6fdc8',
    storageBucket: 'turassist-6fdc8.firebasestorage.app',
    iosBundleId: 'com.natanzdev.turassist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDs-z7FSBZbIePCAR9ksfTEvq8URHt04ss',
    appId: '1:138121353976:web:ffa81bbc3d952fa58f790d',
    messagingSenderId: '138121353976',
    projectId: 'turassist-6fdc8',
    authDomain: 'turassist-6fdc8.firebaseapp.com',
    storageBucket: 'turassist-6fdc8.firebasestorage.app',
    measurementId: 'G-39GSZ2XHFY',
  );
}
