const Map<String, String> cityImageUrls = {
  'Adana':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Adana_Roman_Bridge_%28Ta%C5%9Fk%C3%B6pr%C3%BC%29%2C_Turkey_%2836694356272%29.jpg/800px-Adana_Roman_Bridge_%28Ta%C5%9Fk%C3%B6pr%C3%BC%29%2C_Turkey_%2836694356272%29.jpg',
  'Adıyaman':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/AdiyamanView.jpg/800px-AdiyamanView.jpg',
  'Afyonkarahisar':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Afyonkarahisar_evleri%2C_2019_49.jpg/800px-Afyonkarahisar_evleri%2C_2019_49.jpg',
  'Ağrı':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/00_3411_%C4%B0shak_Pa%C5%9Fa_Saray%C4%B1_-_Turkey.jpg/800px-00_3411_%C4%B0shak_Pa%C5%9Fa_Saray%C4%B1_-_Turkey.jpg',
  'Aksaray':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/AksarayClockTower.jpg/800px-AksarayClockTower.jpg',
  'Amasya':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Ye%C5%9Fil%C4%B1rmak2.jpg/800px-Ye%C5%9Fil%C4%B1rmak2.jpg',
  'Ankara':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Ankara_from_bus_station.jpg/800px-Ankara_from_bus_station.jpg',
  'Antalya':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Falezlerden_Antalya_Konyaalt%C4%B1_Plaj%C4%B1na_do%C4%9Fru_bir_g%C3%B6r%C3%BCn%C3%BCm.jpg/800px-Falezlerden_Antalya_Konyaalt%C4%B1_Plaj%C4%B1na_do%C4%9Fru_bir_g%C3%B6r%C3%BCn%C3%BCm.jpg',
  'Ardahan':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Ardahan.JPG/800px-Ardahan.JPG',
  'Artvin':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/A%C3%87%C3%9C_%C5%9Eehir_Yerle%C5%9Fkesi.jpg/800px-A%C3%87%C3%9C_%C5%9Eehir_Yerle%C5%9Fkesi.jpg',
  'Aydın':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Ayd%C4%B1n%2C_Turkey_03.jpg/800px-Ayd%C4%B1n%2C_Turkey_03.jpg',
  'Balıkesir':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Bal%C4%B1kesirSaatKulesi.jpg/800px-Bal%C4%B1kesirSaatKulesi.jpg',
  'Bartın':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Amasra_%289310207038%29.jpg/800px-Amasra_%289310207038%29.jpg',
  'Batman':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Batman%C3%AA-3.jpg/800px-Batman%C3%AA-3.jpg',
  'Bayburt':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Bayburt%2C_69000_Bayburt_Merkez-Bayburt%2C_Turkey_-_panoramio_%284%29.jpg/800px-Bayburt%2C_69000_Bayburt_Merkez-Bayburt%2C_Turkey_-_panoramio_%284%29.jpg',
  'Bilecik':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Bilecik.jpg/800px-Bilecik.jpg',
  'Bingöl':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Bingolcitycenter.jpg/800px-Bingolcitycenter.jpg',
  'Bitlis':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Bitlis_Montage.jpg/800px-Bitlis_Montage.jpg',
  'Bolu':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/TR_Bolu_asv2021-10_img23_Beyaz%C4%B1t_Mosque.jpg/800px-TR_Bolu_asv2021-10_img23_Beyaz%C4%B1t_Mosque.jpg',
  'Burdur':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Burdur_manzara_-_panoramio.jpg/800px-Burdur_manzara_-_panoramio.jpg',
  'Bursa':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Bursa_image.jpg/800px-Bursa_image.jpg',
  'Çanakkale':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Havadan_cnk.jpg/800px-Havadan_cnk.jpg',
  'Çankırı':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/General_view_of_%C3%87ank%C4%B1r%C4%B1.jpeg/800px-General_view_of_%C3%87ank%C4%B1r%C4%B1.jpeg',
  'Çorum':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/CorumMuseum1.jpg/800px-CorumMuseum1.jpg',
  'Denizli':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/TR_Denizli_asv2020-02_img11_view_from_Teleferik_viewpoint.jpg/800px-TR_Denizli_asv2020-02_img11_view_from_Teleferik_viewpoint.jpg',
  'Diyarbakır':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Goletli_Park%2C_Diyarbakir.jpg/800px-Goletli_Park%2C_Diyarbakir.jpg',
  'Düzce':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/645x344-1573480687396.jpg/640px-645x344-1573480687396.jpg',
  'Edirne':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Selimiye_Mosque_and_The_Statue_of_Architect_Sinan_-_panoramio.jpg/800px-Selimiye_Mosque_and_The_Statue_of_Architect_Sinan_-_panoramio.jpg',
  'Elazığ':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Elaz%C4%B1%C4%9F_City_Center.jpg/800px-Elaz%C4%B1%C4%9F_City_Center.jpg',
  'Erzincan':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Erzincanmerkezi.jpg/800px-Erzincanmerkezi.jpg',
  'Erzurum':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Erzurum_Citadel_-_Erzurum_Kalesi_01.jpg/800px-Erzurum_Citadel_-_Erzurum_Kalesi_01.jpg',
  'Eskişehir':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Sazova_Park_2.jpg/800px-Sazova_Park_2.jpg',
  'Gaziantep':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/AntepKale2_%28cropped%29.jpg/800px-AntepKale2_%28cropped%29.jpg',
  'Giresun':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Giresun_Kalesinden_Giresun-Do%C4%9Fu_Taraf%C4%B1.jpg/800px-Giresun_Kalesinden_Giresun-Do%C4%9Fu_Taraf%C4%B1.jpg',
  'Gümüşhane':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/G%C3%BCm%C3%BC%C5%9Fhane_Genel.JPG/800px-G%C3%BCm%C3%BC%C5%9Fhane_Genel.JPG',
  'Hakkâri':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Hakkari.jpg/800px-Hakkari.jpg',
  'Hatay':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Habib%27i_Neccar_Mosque.jpg/800px-Habib%27i_Neccar_Mosque.jpg',
  'Iğdır':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/I%C4%9Fd%C4%B1r_ve_A%C4%9Fr%C4%B1_Da%C4%9F%C4%B1.jpg/800px-I%C4%9Fd%C4%B1r_ve_A%C4%9Fr%C4%B1_Da%C4%9F%C4%B1.jpg',
  'Isparta':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/DaglardanIsparta.jpg/800px-DaglardanIsparta.jpg',
  'İstanbul':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Historical_peninsula_and_modern_skyline_of_Istanbul.jpg/800px-Historical_peninsula_and_modern_skyline_of_Istanbul.jpg',
  'İzmir':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Bayrakl%C4%B1_Sahil.jpg/800px-Bayrakl%C4%B1_Sahil.jpg',
  'Kahramanmaraş':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Kahramanmara%C5%9F_city_center.jpg/800px-Kahramanmara%C5%9F_city_center.jpg',
  'Karabük':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Karab%C3%BCk_view_8028.jpg/800px-Karab%C3%BCk_view_8028.jpg',
  'Karaman':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Karaman_castle_4868.jpg/800px-Karaman_castle_4868.jpg',
  'Kars':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Holy_Apostles_Church_of_Kars_001.jpg/800px-Holy_Apostles_Church_of_Kars_001.jpg',
  'Kastamonu':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Kastamonu1.jpg/800px-Kastamonu1.jpg',
  'Kayseri':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Mount_Erciyes_%28Argaeus%29%2C_Turkey_%2831870998063%29.jpg/800px-Mount_Erciyes_%28Argaeus%29%2C_Turkey_%2831870998063%29.jpg',
  'Kırıkkale':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/K%C4%B1r%C4%B1kkale_Saat_Kulesi.jpg/800px-K%C4%B1r%C4%B1kkale_Saat_Kulesi.jpg',
  'Kırklareli':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/K%C4%B1rklareli_5195.jpg/800px-K%C4%B1rklareli_5195.jpg',
  'Kırşehir':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Kentpark_2.jpg/800px-Kentpark_2.jpg',
  'Kilis':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Kilis_city_center.jpg/800px-Kilis_city_center.jpg',
  'Kocaeli':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/The_Kocaeli_Sign_in_%C4%B0zmit_City_Center_01.06.2025_02.jpg/800px-The_Kocaeli_Sign_in_%C4%B0zmit_City_Center_01.06.2025_02.jpg',
  'Konya':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Konyaaltincarsi.jpg/800px-Konyaaltincarsi.jpg',
  'Kütahya':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/K%C3%BCtahya_Portesi.png/800px-K%C3%BCtahya_Portesi.png',
  'Malatya':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Malatya_Yeni_Cami_2076.jpg/800px-Malatya_Yeni_Cami_2076.jpg',
  'Manisa':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/MAN%C4%B0Sa.jpg/800px-MAN%C4%B0Sa.jpg',
  'Mardin':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Mardin%2C_Mardin_Merkez-Mardin%2C_Turkey_-_panoramio_%281%29.jpg/800px-Mardin%2C_Mardin_Merkez-Mardin%2C_Turkey_-_panoramio_%281%29.jpg',
  'Mersin':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Mersin-tekneler.jpg/800px-Mersin-tekneler.jpg',
  'Muğla':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Mu%C4%9Fla_fortress_hill_5810.jpg/800px-Mu%C4%9Fla_fortress_hill_5810.jpg',
  'Muş':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Mush_1213.jpg/800px-Mush_1213.jpg',
  'Nevşehir':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Nevsehirpanorama.jpg/800px-Nevsehirpanorama.jpg',
  'Niğde':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Nigde_Kale_1228.jpg/800px-Nigde_Kale_1228.jpg',
  'Ordu':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Ordu%2C_Turkey.JPG/800px-Ordu%2C_Turkey.JPG',
  'Osmaniye':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Osmaniye_flag.JPG/800px-Osmaniye_flag.JPG',
  'Rize':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Georgian_Laz_people_monument_in_Rize_%28Modern_Day_Turkey%29.jpg/800px-Georgian_Laz_people_monument_in_Rize_%28Modern_Day_Turkey%29.jpg',
  'Sakarya':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/TR_Sakarya_asv2021-10_img20_Urban_Park.jpg/800px-TR_Sakarya_asv2021-10_img20_Urban_Park.jpg',
  'Samsun':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Samsun_kolaj_%282018%2C_2%29.png/700px-Samsun_kolaj_%282018%2C_2%29.png',
  'Siirt':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/S%C3%AArt.jpg/800px-S%C3%AArt.jpg',
  'Sinop':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Sinop_Overview_2009.JPG/800px-Sinop_Overview_2009.JPG',
  'Sivas':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Sivas_Cumhuriyet_Meydan%C4%B1_in_2011_8145.jpg/800px-Sivas_Cumhuriyet_Meydan%C4%B1_in_2011_8145.jpg',
  'Şanlıurfa':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Mevlid-i_Halil_Mosque_19.jpg/800px-Mevlid-i_Halil_Mosque_19.jpg',
  'Şırnak':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/%C5%9E%C4%B1rnak_%C5%9Fehir_g%C3%B6r%C3%BCn%C3%BCm%C3%BC.jpg/800px-%C5%9E%C4%B1rnak_%C5%9Fehir_g%C3%B6r%C3%BCn%C3%BCm%C3%BC.jpg',
  'Tekirdağ':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Tekirda%C4%9F_Valilik.JPG/800px-Tekirda%C4%9F_Valilik.JPG',
  'Tokat':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Tokat_%C5%9Fehir_panoramas%C4%B1_2012.JPG/800px-Tokat_%C5%9Fehir_panoramas%C4%B1_2012.JPG',
  'Trabzon':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Trebisonda%2C_ex-chiesa_della_panagia_Chrysokephalos%2C_oggi_moschea_fatih%2C_esterno_01.jpg/800px-Trebisonda%2C_ex-chiesa_della_panagia_Chrysokephalos%2C_oggi_moschea_fatih%2C_esterno_01.jpg',
  'Tunceli':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/D%C3%AArsim.jpg/800px-D%C3%AArsim.jpg',
  'Uşak':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Mendepazar%C4%B1.JPG/800px-Mendepazar%C4%B1.JPG',
  'Van':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Ho%C5%9Fap_24_05_2010_Burg.jpg/800px-Ho%C5%9Fap_24_05_2010_Burg.jpg',
  'Yalova':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Umuttur_Yalova.JPG/800px-Umuttur_Yalova.JPG',
  'Yozgat':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Ormanc%C4%B1lar%C4%B1n_Emekleri_Burada_-_panoramio.jpg/800px-Ormanc%C4%B1lar%C4%B1n_Emekleri_Burada_-_panoramio.jpg',
  'Zonguldak':
      'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Zonguldak_58.jpg/800px-Zonguldak_58.jpg',
};
